trigger:
- main

# Use a Microsoft-hosted agent
pool:
  name : Default

variables:
  imageName: webcloudnexus
  acrLoginServer: cloudnexusacr.azurecr.io
  tag: latest

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install dependencies & build
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Step 3: Build and push Docker image to ACR
- task: Docker@2
  inputs:
    containerRegistry: 'cn'   # ← exact service connection name
    repository: $(acrLoginServer)/$(imageName)
    command: buildAndPush
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
